server:
  port: 8083

app:
  admin:
    username: ${ADMIN_USER:admin}
    password: ${ADMIN_PASS:change-me-now}
  kiosk:
    key: test123

spring:
  datasource:
    url: jdbc:mariadb://pse-db:3307/timeclock?useUnicode=true&characterEncoding=utf8&useServerPrepStmts=true
    #TODO: hide password in production
    username: timeclock_app
    password: ?1r8G7|bBV+T!L9y
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate #important for Flyway
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
